sudo: required
os:
- linux
language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_f1b01b43e7a5_key -iv $encrypted_f1b01b43e7a5_iv
  -in ./tests/rc.tar.enc -out rc.tar -d || true
- tar xvf rc.tar
- npm install -g npm@latest
install:
- npm ci
before_script:
- npm run build
script:
- npm run lint
- npm run test
after_success: npm run coverage
