sudo: required
os:
- linux
language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_24f652ca329e_key -iv $encrypted_24f652ca329e_iv
  -in ./tests/.sheetbaserc.json.enc -out .sheetbaserc.json -d || true
- openssl aes-256-cbc -K $encrypted_24f652ca329e_key -iv $encrypted_24f652ca329e_iv
  -in ./tests/.googlerc.json.enc -out .googlerc.json -d || true
- npm install -g npm@latest
install:
- npm ci
before_script:
- npm run build
script:
- npm run lint
- npm run test
after_success: npm run coverage
